version: '3'

services:
  db:
    image: postgres:14-alpine3.17
    container_name: db_spa
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d postgres -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: app_spa
    env_file:
      - .env
    tty: true
    command: bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - media:/docker_code/media/
      - ./.env.docker:/code/.env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_spa
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - '6380:6379'
      - '9999:8001'

volumes:
  postgres_data:
  redis_data:
  media:
